# syntax=docker/dockerfile:1.6
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore src/api/HearLoveen.Api/HearLoveen.Api.csproj
RUN dotnet publish src/api/HearLoveen.Api/HearLoveen.Api.csproj -c Release -o /out /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /out .
ENTRYPOINT ["dotnet", "HearLoveen.Api.dll"]
