FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5004

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["src/UserService/UserService.csproj", "src/UserService/"]
COPY ["src/core/HearLoveen.Domain/HearLoveen.Domain.csproj", "src/core/HearLoveen.Domain/"]
COPY ["src/infrastructure/HearLoveen.Infrastructure/HearLoveen.Infrastructure.csproj", "src/infrastructure/HearLoveen.Infrastructure/"]
RUN dotnet restore "src/UserService/UserService.csproj"
COPY . .
WORKDIR "/src/src/UserService"
RUN dotnet build "UserService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "UserService.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:5004
ENTRYPOINT ["dotnet", "UserService.dll"]
